php:
  build: .
  ports:
   - "89:80"
   - "4496:443"
  volumes:
   - ./www:/var/www/html
  links:
   - db
db:
  image: mysql:5.7
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=phprs
   - MYSQL_DATABASE=phprs
